// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPcQALWG_G4Wx7yi9j8CmWqm1U_dN-cok',
    appId: '1:823832273903:web:2a23725a365e2f436e4c1a',
    messagingSenderId: '823832273903',
    projectId: 'app-clone-57a0c',
    authDomain: 'app-clone-57a0c.firebaseapp.com',
    storageBucket: 'app-clone-57a0c.appspot.com',
    measurementId: 'G-LR3LFYBT14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBulZu3APUKw2Jwitu-SDi8WSDuzqGP_ms',
    appId: '1:823832273903:android:d255be5c47c44d676e4c1a',
    messagingSenderId: '823832273903',
    projectId: 'app-clone-57a0c',
    storageBucket: 'app-clone-57a0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0wVkAaEt7sggAkkE-Xg81L8X84pia4d8',
    appId: '1:823832273903:ios:0e3ced93d0cc8ef06e4c1a',
    messagingSenderId: '823832273903',
    projectId: 'app-clone-57a0c',
    storageBucket: 'app-clone-57a0c.appspot.com',
    iosClientId: '823832273903-ovaveejk0l7v4nsb9hln1csmfh1908m8.apps.googleusercontent.com',
    iosBundleId: 'com.example.appClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0wVkAaEt7sggAkkE-Xg81L8X84pia4d8',
    appId: '1:823832273903:ios:0e3ced93d0cc8ef06e4c1a',
    messagingSenderId: '823832273903',
    projectId: 'app-clone-57a0c',
    storageBucket: 'app-clone-57a0c.appspot.com',
    iosClientId: '823832273903-ovaveejk0l7v4nsb9hln1csmfh1908m8.apps.googleusercontent.com',
    iosBundleId: 'com.example.appClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPcQALWG_G4Wx7yi9j8CmWqm1U_dN-cok',
    appId: '1:823832273903:web:48db9d02d1bfd4536e4c1a',
    messagingSenderId: '823832273903',
    projectId: 'app-clone-57a0c',
    authDomain: 'app-clone-57a0c.firebaseapp.com',
    storageBucket: 'app-clone-57a0c.appspot.com',
    measurementId: 'G-YXNW2SNF47',
  );
}
